/**
 * Just enough XML to read UPnP.
 *
 * A dependency was considered and rejected: what has to be read here is a
 * device description and a handful of SOAP envelopes, both flat, both
 * generated by the same small set of router firmwares. A general XML parser
 * would be the largest thing in the binary and would still need this much
 * code wrapped around it to find the elements by local name.
 *
 * This is deliberately not a general parser. It finds elements by local name
 * and decodes their text. It does not understand namespaces properly, nested
 * elements of the same name, or CDATA - none of which appear in what UPnP
 * sends.
 */

/** Matches an element by local name, ignoring whatever namespace prefix it carries. */
function pattern(name: string): RegExp {
  const local = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(
    `<(?:[\\w.-]+:)?${local}(?:\\s[^>]*)?(?:/>|>([\\s\\S]*?)</(?:[\\w.-]+:)?${local}\\s*>)`,
    "gi",
  );
}

/** The inner content of every element with this local name, in document order. */
export function elements(xml: string, name: string): string[] {
  return [...xml.matchAll(pattern(name))].map((match) => match[1] ?? "");
}

/** The decoded text of the first element with this local name. */
export function text(xml: string, name: string): string | undefined {
  const found = pattern(name).exec(xml);
  return found ? decode(found[1] ?? "") : undefined;
}

const ENTITIES: Readonly<Record<string, string>> = {
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  apos: "'",
};

/**
 * Decode XML entities.
 *
 * Descriptions come back through here, and other tools sharing the router put
 * ampersands and quotes in theirs. A description that decodes differently from
 * how it was encoded would compare unequal to itself.
 */
export function decode(value: string): string {
  return value.replace(/&(#x?[0-9a-f]+|[a-z]+);/gi, (whole, entity: string) => {
    if (entity.startsWith("#")) {
      const code = entity[1]?.toLowerCase() === "x"
        ? Number.parseInt(entity.slice(2), 16)
        : Number.parseInt(entity.slice(1), 10);
      return Number.isNaN(code) ? whole : String.fromCodePoint(code);
    }
    return ENTITIES[entity.toLowerCase()] ?? whole;
  });
}

/**
 * Encode text for an XML element body.
 *
 * Container names reach the router inside a rule description, and Docker
 * permits characters there that would otherwise close the element early.
 */
export function encode(value: string): string {
  return value.replace(/[&<>"']/g, (character) => {
    switch (character) {
      case "&": return "&amp;";
      case "<": return "&lt;";
      case ">": return "&gt;";
      case '"': return "&quot;";
      default: return "&apos;";
    }
  });
}
